# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='img_description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='img_license',
            field=models.CharField(choices=[('RIG', 'Copyright'), ('LEF', 'Copyleft'), ('CC', 'Creative Commons')], default='RIG', max_length=3),
        ),
        migrations.AddField(
            model_name='post',
            name='img_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='img_name',
            field=models.CharField(blank=True, max_length=65),
        ),
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.URLField(blank=True),
        ),
    ]
